services:
  sentiment-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
