[project]
name = "mlops-cs317-p21"
version = "0.1.0"
description = "Sentiment Analysis"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlflow>=2.22.0",
    "nltk>=3.9.1",
    "optuna>=4.3.0",
    "prefect>=3.4.2",
    "seaborn>=0.13.2",
]
