global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true

route:
  receiver: "null-receiver"
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m
  group_by: ["alertname"]

  routes:
    - matchers:
        - action="retrain"
      receiver: "retraining-service"

receivers:
  - name: "null-receiver"

  - name: "retraining-service"
    webhook_configs:
      - url: "http://retraining-service:8080/trigger-retrain"
        send_resolved: false
        max_alerts: 0
        http_config:
          follow_redirects: true

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname"]
