{
 "title": "System Monitoring",
 "tags": [
  "system",
  "node-exporter",
  "gpu"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[3m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "GPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "avg by (gpu)(nvidia_gpu_utilization{job=\"dcgm\"})",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Network I/O (B/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[3m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[3m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used (%)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!=\"tmpfs\",mountpoint!~\"/(sys|proc|dev)($|/.*)\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\",mountpoint!~\"/(sys|proc|dev)($|/.*)\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\",mountpoint!~\"/(sys|proc|dev)($|/.*)\"} * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O (B/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[3m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[3m]))",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}