global:
  scrape_interval: 30s
  evaluation_interval: 15s

rule_files:
  - ./rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "sentiment-api"
    static_configs:
      - targets: ["sentiment-api:8000"]
    scrape_interval: 15s
    scrape_timeout: 10s
