groups:
  - name: sentiment_api_alerts
    rules:
      - alert: TestRetrainingAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
          action: retrain
        annotations:
          summary: "Test retraining alert"
          description: "This alert is always firing to test the retraining pipeline"

      - alert: HighErrorRate
        expr: (sum(rate(sentiment_api_http_requests_total{status=~"5.."}[5m])) / sum(rate(sentiment_api_http_requests_total[5m]))) * 100 > 50
        for: 2m
        labels:
          severity: critical
          action: retrain
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 50% (current value: {{ $value }}%)"

      - alert: LowConfidenceScore
        expr: avg(model_confidence_score_bucket{le="0.6"}) / avg(model_confidence_score_count) > 0.3
        for: 5m
        labels:
          severity: warning
          component: "ml-model"
          action: retrain
        annotations:
          summary: "Low confidence score detected"
          description: "More than 30% of predictions have confidence below 0.6 (current value: {{ $value }})"

      - alert: SlowInferenceTime
        expr: avg(rate(model_inference_time_seconds_sum[5m]) / rate(model_inference_time_seconds_count[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
          component: "ml-model"
          action: retrain
        annotations:
          summary: "Slow model inference detected"
          description: "Average inference time is over 500ms (current value: {{ $value }}s)"

      - alert: HighRequestLatency
        expr: histogram_quantile(0.9, sum(rate(sentiment_api_http_request_duration_seconds_bucket{handler="/predict"}[5m])) by (le)) > 1
        for: 2m
        labels:
          severity: warning
          component: "api"
        annotations:
          summary: "High API latency detected"
          description: "90% of requests to /predict endpoint take longer than 1 second (current value: {{ $value }}s)"

  - name: node_alerts
    rules:
      - alert: HighCPULoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load"
          description: "CPU load is above 80% (current value: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% (current value: {{ $value }}%)"
